services:
  lib81:
    build:
      context: docker/8.1
      dockerfile: "Dockerfile"
      args:
        UID: ${USER_ID}
    container_name: ${LIBRARY_NAME}-lib81
    working_dir: /src
    volumes:
      - ./:/src
    env_file:
      - .env

  lib84:
    build:
      context: docker/8.4
      dockerfile: "Dockerfile"
      args:
        UID: ${USER_ID}
    container_name: ${LIBRARY_NAME}-lib84
    working_dir: /src
    volumes:
      - ./:/src
    env_file:
      - .env